# dbt_project.yml

name: 'flow_data_pipeline'
version: '1.0.0'
profile: 'flow_data_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  flow_data_pipeline:

    # Configuration for the 'bronze' directory
    bronze:
      +schema: bronze           # Maps to 'bronze' schema
      +materialized: incremental
      +incremental_strategy: merge
      +on_schema_change: sync_all_columns

    # Configuration for the 'silver' directory
    silver:
      +schema: silver           # Maps to 'silver' schema
      +materialized: incremental
      +incremental_strategy: merge
      +on_schema_change: sync_all_columns
